### ISSUE TITLE
Implement better patch for horizontal scrollbar

### ISSUE THREAD

**Issue by Tjoosten** [Misfits-BE/kinderrechten.activisme.be#10]
For now there is applied a dirty fix 

```css
body {
  overflow-x: hidden;
  overflow-y: scroll;
}
```

at the welcome.blade.php We need to look out for a better solution,
